name: Merge project.json if it exists and deploy on main

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'project.json'

jobs:
  merge-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge project.json into main
        run: |
          git checkout main
          git merge "${{ github.ref }}"
          git push origin main
      - name: Deploy on main
        if: success()
        run: |
          npm run build
          echo "Deployment on main branch"
