name: Generate Index JSON

on:
  push:
    branches:
      - main

jobs:
  generate-index-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.3

      - name: Set up Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'

      - name: Run Generate Index JSON
        run: |
          node generate-index-json.js
