name: Generate Index JSON

on:
  push:
    branches:
      - main

jobs:
  generate-index-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Generate Index JSON
        run: node .github/actions/generate-index-json.js
